### ISSUE TITLE
Go through new repo checklist

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/papyrus#20]

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/phet-info/blob/master/checklists/new-repo-checklist.md

**Comment by jessegreenberg** [comment]
From the checklist, the things that apply are:
- [ ] Go to Settings => Collaborators and teams. Press the "Add teams" button. See [team assignment.md](https://github.com/phetsims/phet-info/blob/master/policies/team%20assignment.md) for assignments by repo type.
- [ ] Apply GitHub labels. See [github-labels/README.md](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md).
- [ ] Apply branch protection rules using [protect-branches-for-repo.js](https://github.com/phetsims/perennial/blob/master/js/scripts/protect-branches-for-repo.js). Follow the instructions in the documentation at the top of the script.
- [ ] Add the repo to [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json).

Over slack we discussed not adding this repo to active-repos for now because it will be in our sub team for now, is a very large repo, and will not be a sim or sim dependency.

**Comment by jessegreenberg** [comment]
Items above done.
